print("================================")
print ("nama\t: Muhamad Nur Raply")
print("NIM\t: 0110223098")
print("Kelas\t: TEKNIK INFORMATIKA 03")
print("Alamat\t: DS.Pasir Jambu kab.Bogor ")
print("================================")