print("================================")
print ("nama\t: Indri Rachma")
print("NIM\t: 0110223101")
print("Kelas\t: TEKNIK INFORMATIKA 03")
print("Alamat\t:Bogor ")
print("================================")