print("-------------------------------------------------")
#soal no 3
# Variable 
bilangan1 = 12
bilangan2 = 7
#cetak hasil penjumlahan bilangan1 dan bilangan2
print("hasil penjumlahan\t:",bilangan1+bilangan2)
print("-------------------------------------------------")

print("-------------------------------------------------")
#soal no 4
# Variable 
bilangan1 = 14
bilangan2 = 8
#cetak hasil pembagian bilangan1 dan bilangan2
print("hasil pengurangan\t:",bilangan1-bilangan2)
print("-------------------------------------------------")

print("-------------------------------------------------")
#soal no 5
# Variable 
bilangan1 = 18
bilangan2 = 9
bilangan3 = 8
#cetak hasil perkalian bilangan1,bilangan2 dan bilangan3
print("hasil perkalian\t\t:",bilangan1*bilangan2*bilangan3)
print("-------------------------------------------------")

print("-------------------------------------------------")
#soal no 6
# Variable 
bilangan1 = 90
bilangan2 = 10
#cetak hasil pembagian bilangan1 dan bilangan2
print("hasil pembagian\t\t:",bilangan1/bilangan2)
print("-------------------------------------------------")